# Generated by Django 3.2.11 on 2022-01-29 19:29

from django.db import migrations


def seed_menu_categories(apps, schema_editor):
    categories = [
        {"id": 1, "image_id": "f3fbf57b118fa9", "name": "Bakery"},
        {"id": 2, "image_id": "b271afbefdc554", "name": "Entrees"},
        {"id": 3, "image_id": "eba73b2361fae3", "name": "Drinks"},
    ]

    Category = apps.get_model("menu", "Category")
    Image = apps.get_model("menu", "Image")
    for category in categories:
        image = Image.objects.get(name=category["image_id"])
        Category.objects.create(id=category["id"], image=image, name=category["name"])


def clear_menu_categories(apps, schema_editor):
    Category = apps.get_model("menu", "Category")
    for category in Category.objects.all():
        category.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_seed_menu_images"),
    ]

    operations = [
        migrations.RunPython(seed_menu_categories, reverse_code=clear_menu_categories),
    ]
