# Generated by Django 3.2.11 on 2022-01-29 19:35

from django.db import migrations


def seed_menu_items(apps, schema_editor):
    items = [
        {
            "category_id": 1,
            "id": 1,
            "image_id": "293202f9d9f7f4",
            "name": "Bagel",
            "price": 2.0,
        },
        {
            "category_id": 1,
            "id": 2,
            "image_id": "808916fd5ddf96",
            "name": "Croissant",
            "price": 1.0,
        },
        {
            "category_id": 1,
            "id": 3,
            "image_id": "95d02a230fe050",
            "name": "Muffin",
            "price": 1.25,
        },
        {
            "category_id": 1,
            "id": 4,
            "image_id": "23f95765b967ff",
            "name": "Toast / Bread",
            "price": 1,
        },
        {
            "category_id": 1,
            "id": 5,
            "image_id": "5650be5d48a99b",
            "name": "English Muffin",
            "price": 2.5,
        },
        {
            "category_id": 2,
            "id": 6,
            "image_id": "bd237a0c0d19ef",
            "name": "Pasta Bar",
            "price": 12.99,
        },
        {
            "category_id": 2,
            "id": 7,
            "image_id": "3e1bd1342800f7",
            "name": "Mediterranean Entree",
            "price": 10.99,
        },
        {
            "category_id": 2,
            "id": 8,
            "image_id": "72589c4c990f97",
            "name": "Indian Entree",
            "price": 11.95,
        },
        {
            "category_id": 3,
            "id": 9,
            "image_id": "70c2a6247e7b58",
            "name": "Small Drink",
            "price": 0.75,
        },
        {
            "category_id": 3,
            "id": 10,
            "image_id": "dba0fc03da30ca",
            "name": "Medium Drink",
            "price": 1.5,
        },
        {
            "category_id": 3,
            "id": 11,
            "image_id": "ffc9bf61e441cd",
            "name": "Large Drink",
            "price": 2,
        },
    ]

    MenuItem = apps.get_model("menu", "MenuItem")
    Category = apps.get_model("menu", "Category")
    Image = apps.get_model("menu", "Image")
    for item in items:
        image = Image.objects.get(name=item["image_id"])
        category = Category.objects.get(id=item["category_id"])
        MenuItem.objects.create(
            id=item["id"],
            image=image,
            category=category,
            name=item["name"],
            price=item["price"],
        )


def clear_menu_items(apps, schema_editor):
    MenuItem = apps.get_model("menu", "MenuItem")
    for item in MenuItem.objects.all():
        item.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_seed_menu_categories"),
    ]

    operations = [
        migrations.RunPython(seed_menu_items, reverse_code=clear_menu_items),
    ]
